### ISSUE TITLE
FYI Birthday Attacks aren't important in CTR mode

### ISSUE THREAD

**Issue by ryazo** [qgustavor/generic-speck#1]
Since this is for integer  obfuscation, and I assume that you are using a generalized speck without initialization vectors (a common way to reuse a single key), birthday attacks shouldn't be important.

Rather it is the codebook attack (a known plaintext and ciphertext attack), which is less significant.

Anyway, emphasizing any cryptanalysis isn't important, this is only for obfuscation.

**Comment by qgustavor** [comment]
Well, as no block mode of operation was implemented it's ECB mode. I don't know so much about attacks against block ciphers so I based that part of the readme on the second point of [this answer](https://crypto.stackexchange.com/a/8570) and a quick read from the first two sections of [this page](https://sweet32.info/).

I want to avoid people thinking this is a Speck implementation made for encryption/decryption. As I wrote on the research section of the readme I just choose it because it was simple to implement and it was possible to make it work with various block sizes. I didn't tested it against any attacks and I don't if it's vulnerable to those, the only tests I did are those on test.js and checking it against test vectors from the specification PDF (the first test vector is the one from the example in the readme).

If you can improve the readme you can send a pull request.
